# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='emotion_type',
            field=models.CharField(choices=[('joy', 'Joy'), ('sorrow', 'Sorrow'), ('anger', 'Anger'), ('surprise', 'Surprise')], max_length=12, verbose_name='Emotion type'),
        ),
    ]
